[package]
name = "onepack"
version = "1.0.0"
edition = "2024.beta"

[dependencies]
One = { local = "../onechain/crates/sui-framework/packages/one-framework" }
MoveStdlib = { local = "../onechain/crates/sui-framework/packages/move-stdlib" }

[addresses]
onepack = "0x0"
one = "0x2"
std = "0x1"
